version: 0.2
phases:
  install:
    runtime-versions:
        java: 8
  build:
    commands:
      - mvn package shade:shade
      - export BUCKET=lambda-deployment-artifacts-arunagassi
      - aws cloudformation package --template-file template.yml --s3-bucket $BUCKET
artifacts:
  type: zip
  files:
    - template.yml