version: 0.2
phases:
  install:
    runtime-versions:
        java: corretto8
  build:
    commands:
      - mvn package shade:shade
      - aws s3 ls
      - export BUCKET=lambda-deployment-artifacts-arunagassi
      - aws cloudformation package --template-file template.yml --s3-bucket $BUCKET --output-template-file outputtemplate.yml
artifacts:
  type: jar
  files:
    - template.yml
    - outputtemplate.yml
    - target/lambda-0.0.1-SNAPSHOT-shaded.jar